In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


In [2]:
train=pd.read_csv('/home/ashwani/Desktop/Python/DataSet/train/trains_train.csv')
test=pd.read_csv('/home/ashwani/Desktop/Python/DataSet/train/trains_test.csv')


In [3]:
train.head()

date         time               connection       from         to  \
0  2016-07-27  08:05:51 PM  8813003/20160727/IC1518  008813003  000000000   
1  2016-07-27  08:06:11 PM  8813003/20160727/IC1518  008813003  000000000   
2  2016-07-27  08:08:57 PM  8813003/20160727/IC1518  008813003  000000000   
3  2016-07-27  08:09:08 PM  8813003/20160727/IC1518  008813003  000000000   
4  2016-07-27  08:11:01 PM  8813003/20160727/IC1518  008813003  000000000   

  vehicle occupancy  
0  IC1518      high  
1  IC1518      high  
2  IC1518      high  
3  IC1518      high  
4  IC1518      high

In [4]:
# Splitting Connection Variables
train_con= pd.DataFrame(train.connection.str.split('/',2).tolist(),
                                  columns = ['frm','mid','vech'])

In [5]:
train_con.head()

frm       mid    vech
0  8813003  20160727  IC1518
1  8813003  20160727  IC1518
2  8813003  20160727  IC1518
3  8813003  20160727  IC1518
4  8813003  20160727  IC1518

In [6]:
train=train.drop(['vehicle'], axis=1)
train['vehicle']=train_con.vech

In [7]:
test_con= pd.DataFrame(test.connection.str.split('/',2).tolist(),
                                  columns = ['frm','mid','vech'])

In [8]:
test_con.tail()

frm       mid    vech
1524  8892007  20161219  IC1806
1525  8821006  20161219  IC2028
1526  8833308  20161219  IC1728
1527  8814001  20161219   P7801
1528  8814167  20161219   P7723

In [9]:
test=test.drop(['vehicle'], axis=1)
test['vehicle']=test_con.vech

In [10]:
train['from'].mode()[0]
train.loc[train['from']=='(null)','from']=8812005
train.loc[train['to']=='(null)','to']=0


'008892007'

In [11]:
#train[train['vehicle']=='IC1518']
train.loc[train['to']==0, 'to']=8831765

In [12]:
train.shape, test.shape

((2250, 7), (1529, 6))

In [13]:
print(train.dtypes)
test.dtypes

date          object
time          object
connection    object
from          object
to            object
occupancy     object
vehicle       object
dtype: object


date          object
time          object
connection    object
from           int64
to             int64
vehicle       object
dtype: object

In [14]:
train['date']=pd.to_datetime(train['date'])
train['month'] = train['date'].dt.month
train['days_week']=train['date'].dt.dayofweek
train['week_day'] = train['date']. dt.weekday_name
train['day'] = train['date'].dt.day
train['time']=pd.to_datetime(train.time)
train['seconds']=train['time'].dt.second
train['hour']=train['time'].dt.hour
train['minutes']=train['time'].dt.minute
train['hour_minutes']=train['hour']*60+ train['minutes']+train['seconds']/60

In [15]:
test['date']=pd.to_datetime(test['date'])
test['month'] = test.date.dt.month
test['days_week']=test.date.dt.dayofweek
test['week_day'] = test.date.dt.weekday_name
test['day'] = test['date'].dt.day
test.time=pd.to_datetime(test.time)
test['seconds']=test['time'].dt.second
test['hour']=test['time'].dt.hour
test['minutes']=test['time'].dt.minute

test['hour_minutes']=test['hour']*60+ test['minutes']+test['seconds']/60

In [16]:
train.dtypes

date            datetime64[ns]
time            datetime64[ns]
connection              object
from                    object
to                      object
occupancy               object
vehicle                 object
month                    int64
days_week                int64
week_day                object
day                      int64
seconds                  int64
hour                     int64
minutes                  int64
hour_minutes           float64
dtype: object

In [17]:
train.head()

date                time               connection       from  \
0 2016-07-27 2017-09-30 20:05:51  8813003/20160727/IC1518  008813003   
1 2016-07-27 2017-09-30 20:06:11  8813003/20160727/IC1518  008813003   
2 2016-07-27 2017-09-30 20:08:57  8813003/20160727/IC1518  008813003   
3 2016-07-27 2017-09-30 20:09:08  8813003/20160727/IC1518  008813003   
4 2016-07-27 2017-09-30 20:11:01  8813003/20160727/IC1518  008813003   

          to occupancy vehicle  month  days_week   week_day  day  seconds  \
0  000000000      high  IC1518      7          2  Wednesday   27       51   
1  000000000      high  IC1518      7          2  Wednesday   27       11   
2  000000000      high  IC1518      7          2  Wednesday   27       57   
3  000000000      high  IC1518      7          2  Wednesday   27        8   
4  000000000      high  IC1518      7          2  Wednesday   27        1   

   hour  minutes  hour_minutes  
0    20        5   1205.850000  
1    20        6   1206.183333  
2    20        8   1208.950000  
3    20        9   1209.133333  
4    20       11   1211.016667

In [18]:
x=train.loc[:, ['week_day','month','day','from', 'to','vehicle','hour_minutes','occupancy']]
y=test.loc[:, ['week_day','month','day','from', 'to','vehicle','hour_minutes','occupancy']]

final=x.append(y, ignore_index=True)
final.head()

week_day  month  day       from         to vehicle  hour_minutes occupancy
0  Wednesday      7   27  008813003  000000000  IC1518   1205.850000      high
1  Wednesday      7   27  008813003  000000000  IC1518   1206.183333      high
2  Wednesday      7   27  008813003  000000000  IC1518   1208.950000      high
3  Wednesday      7   27  008813003  000000000  IC1518   1209.133333      high
4  Wednesday      7   27  008813003  000000000  IC1518   1211.016667      high

In [19]:
line=pd.read_csv('/home/ashwani/Desktop/Python/DataSet/train/KaggleTrainOccupancy-master/line_info.csv')

In [20]:
line.head()

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1 vehicle_id vehicle_type  \
0           0             0               0    EUR9148          EUR   
1           1             1               1     IC1504           IC   
2           2             2               2     IC1505           IC   
3           3             3               3     IC1506           IC   
4           4             4               4     IC1507           IC   

   nr_of_stops                               stopping_station_ids  
0            3            ['007015400', '008722326', '008814001']  
1           15  ['008891009', '008891140', '008892007', '00881...  
2           16  ['008891405', '008891009', '008891140', '00889...  
3           16  ['008891405', '008891009', '008891140', '00889...  
4           16  ['008891405', '008891009', '008891140', '00889...

In [21]:
final_new = pd.merge(final,line.iloc[:,[3,4,5]], how = 'left', left_on= 'vehicle', right_on= 'vehicle_id')

In [22]:
final_new.head()

week_day  month  day       from         to vehicle  hour_minutes  \
0  Wednesday      7   27  008813003  000000000  IC1518   1205.850000   
1  Wednesday      7   27  008813003  000000000  IC1518   1206.183333   
2  Wednesday      7   27  008813003  000000000  IC1518   1208.950000   
3  Wednesday      7   27  008813003  000000000  IC1518   1209.133333   
4  Wednesday      7   27  008813003  000000000  IC1518   1211.016667   

  occupancy vehicle_id vehicle_type  nr_of_stops  
0      high     IC1518           IC         16.0  
1      high     IC1518           IC         16.0  
2      high     IC1518           IC         16.0  
3      high     IC1518           IC         16.0  
4      high     IC1518           IC         16.0

In [23]:
final_new['vehicle_type']=final_new['vehicle_type'].fillna(final_new['vehicle_type'].dropna().mode()[0])

In [24]:
final_new.vehicle_type.value_counts()

IC     2593
S       540
P       360
L       265
THA      14
ICE       4
TRN       1
TGV       1
EUR       1
Name: vehicle_type, dtype: int64

In [25]:
final_new=final_new.drop(['vehicle_id'],axis=1)

In [26]:
final_new.dtypes

week_day         object
month             int64
day               int64
from             object
to               object
vehicle          object
hour_minutes    float64
occupancy        object
vehicle_type     object
nr_of_stops     float64
dtype: object

In [27]:
cat=[ 'from', 'to','vehicle', 'occupancy','vehicle_type']
for col in cat:
    final_new[col]=final_new[col].astype('category')

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in ['vehicle','week_day','nr_of_stops','vehicle_type']:
    final_new[col] = le.fit_transform(final_new[col])

In [29]:
train=final_new.iloc[0:2250,:]
test=final_new.iloc[2250:, [0,1,2,3,4,5,6,8,9]]

In [30]:
train.shape, test.shape

((2250, 10), (1529, 9))

In [31]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import ensemble
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn import metrics
from sklearn.model_selection import train_test_split

In [32]:
train.head()

week_day  month  day       from         to  vehicle  hour_minutes  \
0         6      7   27  008813003  000000000       46   1205.850000   
1         6      7   27  008813003  000000000       46   1206.183333   
2         6      7   27  008813003  000000000       46   1208.950000   
3         6      7   27  008813003  000000000       46   1209.133333   
4         6      7   27  008813003  000000000       46   1211.016667   

  occupancy  vehicle_type  nr_of_stops  
0      high             1           14  
1      high             1           14  
2      high             1           14  
3      high             1           14  
4      high             1           14

In [34]:
X_train, X_test, Y_train,Y_test = train_test_split(train.drop(['occupancy'],axis=1),
                                                    train['occupancy'],
                                                    test_size =0.3,
                                                    random_state = 123)

In [35]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((1575, 9), (1575,), (675, 9), (675,))

### Decesion Tree

In [36]:
tree_model = DecisionTreeClassifier()
tree_model.fit(X = X_train, y = Y_train)
pred_tree = tree_model.predict(X = X_test)
metrics.confusion_matrix(Y_test,pred_tree)
metrics.accuracy_score(Y_test,pred_tree), metrics.cohen_kappa_score(Y_test,pred_tree)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

array([[115,  64,  48],
       [ 78, 152,  43],
       [ 45,  46,  84]])

(0.52000000000000002, 0.26965616734792019)

### Random Forest

In [37]:
rand_model = RandomForestClassifier(n_estimators=500)
rand_model.fit(X = X_train, y = Y_train)
pred_rand = rand_model.predict(X = X_test)
metrics.confusion_matrix(Y_test,pred_rand)

metrics.accuracy_score(Y_test,pred_rand), metrics.cohen_kappa_score(Y_test,pred_rand),


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=500, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

array([[119,  58,  50],
       [ 50, 185,  38],
       [ 44,  51,  80]])

(0.56888888888888889, 0.339996371114068)

### Gradient Boosting

In [38]:

grad_model = GradientBoostingClassifier()
grad_model.fit(X = X_train, y = Y_train)
pred_grad = grad_model.predict(X = X_test)
metrics.confusion_matrix(Y_test,pred_grad)
metrics.accuracy_score(Y_test,pred_grad), metrics.cohen_kappa_score(Y_test,pred_grad)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=100, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False)

array([[124,  59,  44],
       [ 65, 181,  27],
       [ 52,  58,  65]])

(0.54814814814814816, 0.30392136974073924)

### Bagging

In [39]:
bag_model = ensemble.bagging.BaggingClassifier(n_estimators= 700,  max_features=0.5, max_samples=.6)
bag_model.fit(X = X_train, y = Y_train)
pred_bag = bag_model.predict(X = X_test)
metrics.confusion_matrix(Y_test,pred_bag)
metrics.accuracy_score(Y_test,pred_bag), metrics.cohen_kappa_score(Y_test,pred_bag)

BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=False, max_features=0.5, max_samples=0.6,
         n_estimators=700, n_jobs=1, oob_score=False, random_state=None,
         verbose=0, warm_start=False)

array([[131,  60,  36],
       [ 51, 191,  31],
       [ 37,  65,  73]])

(0.58518518518518514, 0.35963461903342098)

### SVM

In [40]:
from sklearn import svm
from sklearn.preprocessing import scale
X_train=scale(X_train, axis=0)
X_test=scale(X_test, axis=0)
svm_model = svm.SVC()
svm_model.fit(X = X_train, y = Y_train)
pred_svm = svm_model.predict(X_test)
metrics.confusion_matrix(Y_test,pred_svm)
metrics.accuracy_score(Y_test,pred_svm), metrics.cohen_kappa_score(Y_test,pred_svm)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

array([[ 85, 111,  31],
       [ 55, 195,  23],
       [ 47,  92,  36]])

(0.46814814814814815, 0.16084315653872261)

### Here the best result getting through Bagging

In [41]:
#test=test.loc[:,('date','hour_minutes', 'from', 'to','vehicle')]
pred_test=bag_model.predict(test)

In [42]:
output=pd.DataFrame({'id':range(0,len(pred_test)), 'occupancy':pred_test})
output.to_csv('/home/ashwani/Desktop/output.csv', index=False)